[project]
name = "datascience-rtm-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipywidgets>=8.1.5",
    "pandas>=2.0.3",
    "setuptools>=75.9.1",
    "ydata-profiling>=4.13.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]

[tool.uv.workspace]
members = ["datascience-rtm-hackathon"]
